{% set name = "tree-sitter-python" %}
{% set version = "0.23.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tree-sitter/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b38e5b1f5237377b506109978af76422975bda5859165835e3c7b5afee987383

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - tree_sitter_python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tree-sitter/tree-sitter-python
  summary: Python grammar for tree-sitter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
